config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :employees do
    resources :addresses
  end

  resources :users
  resources :departments,      except: [:show]
  resources :job_titles,       except: [:show]
  resources :job_assignments,  except: [:show]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee
	include Mongoid::Document
	field :first_name, 		type: String
	field :middle_name, 	type: String
	field :last_name, 		type: String
	field :birthday, 		type: Date

	belongs_to :department
	has_many :job_assignment, autosave: true
  	embeds_many :addresses
  	accepts_nested_attributes_for :addresses

	validates :first_name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
	validates :last_name, length: { minimum: 5, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :set_employee, only: [:edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: "The employee has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    if @employee.update_attributes(employee_params)
      redirect_to employees_path, notice: 'The employee has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'The employee has been deleted!' and return
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :middle_name, :last_name, :birthday, :department_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def manage_employee(employee)
		first = Employee.first
		return !(first.id == employee)
	end
end

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>

<%= f.label :first_name, 'First Name' %>
<%= f.text_field :first_name, class: 'form-control' %>

<%= f.label :middle_name, 'Middle Name' %>
<%= f.text_field :middle_name, class: 'form-control' %>

<%= f.label :last_name, 'Last Name' %>
<%= f.text_field :last_name, class: 'form-control' %>

<%= f.label :birthday %>
<%= date_field :employee, :birthday, class: 'form-control' %>

<%= f.label :department_id %>
<%= f.collection_select(:department_id, Department.all, :id, :name, {:include_blank => true}, {:class=>'form-control'}) %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/employees/create.html.erb
<h1>Employee#create</h1>
<p>Find me in app/views/employee/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employee#destroy</h1>
<p>Find me in app/views/employee/destroy.html.erb</p>

app/views/employees/edit.html.erb
<% provide(:title, "Edit Employee") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<% provide(:heading, "Employees") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/employees/index.html.erb
<% provide(:title, "Employees") %>
<% provide(:heading, "Employees") %>
<div class="well">
  <%= link_to "New Employee", new_employee_path, class: "btn btn-primary" %>
  <% if @employees.size > 0 %>
    <%= link_to "Assign Job", job_assignments_path, class: "btn btn-warning" %>
  <% end %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Birthday</th>
      <th>Department</th>
      <th>Address</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @employees.size == 0 %>
      <tr>
        <td colspan="8">No employees found.</td>
      </tr>
    <% else %>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name %></td>
          <td><%= employee.middle_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.birthday %></td>
          <% dept = Department.find(employee.department_id) %>
          <td>
            <% if dept.nil? %>
              <%= "Department not found" %>
            <% else  %>
              <%= dept.name %>
            <% end %>
          </td>
          <% if manage_employee(employee.id) %>
            <td>
              <%= link_to "Add", employee_addresses_path(employee), class: "btn btn-default" %>
            </td>
            <td>
              <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-default" %>
            </td>
            <td>
              <%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure you wish to delete this employee?' }, class: "btn btn-danger"  %></td>
            </td>
          <% else %>
            <td></td>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<% provide(:title, "New Employee") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<% provide(:heading, "Employees") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/employees/update.html.erb
<h1>Employee#update</h1>
<p>Find me in app/views/employee/update.html.erb</p>