config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :employees do
    resources :addresses
  end

  resources :users
  resources :departments,      except: [:show]
  resources :job_titles,       except: [:show]
  resources :job_assignments,  except: [:show]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job_title.rb
class JobTitle
  include Mongoid::Document
  field :name, type: String

  has_many :job_assignment, autosave: true

  validates :name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }, :uniqueness => true
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
	before_action :set_job_title, only: [:edit, :update, :destroy]

  def index
    @job_titles = JobTitle.all
  end

  def new
    @job_title = JobTitle.new
  end

  def create
    @job_title = JobTitle.new(job_title_params)

    if @job_title.save
      redirect_to job_titles_path, notice: "The job title has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    if @job_title.update_attributes(job_title_params)
      redirect_to job_titles_path, notice: 'The job title has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @job_title.destroy
    redirect_to job_titles_path, notice: 'The job title has been deleted!' and return
  end

  private
    def set_job_title
      @job_title = JobTitle.find(params[:id])
    end

    def job_title_params
      params.require(:job_title).permit(:name)
    end
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
	def manage_job_title(job_title)
		first = JobTitle.first
		return !(first.id == job_title)
	end
end

app/views/job_titles/_form.html.erb
<%= form_for @job_title do |f| %>

<%= f.label :name, 'Name' %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/job_titles/create.html.erb
<h1>JobTitle#create</h1>
<p>Find me in app/views/job_title/create.html.erb</p>

app/views/job_titles/destroy.html.erb
<h1>JobTitle#destroy</h1>
<p>Find me in app/views/job_title/destroy.html.erb</p>

app/views/job_titles/edit.html.erb
<% provide(:title, "Edit Job Title") %>
<% provide(:button, "Update") %>
<% provide(:kind, "update") %>
<% provide(:heading, "Job Titles") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/job_titles/index.html.erb
<% provide(:title, "Job Titles") %>
<% provide(:heading, "Job Titles") %>
<div class="well">
  <%= link_to "New Job Title", new_job_title_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Job Title</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @job_titles.size == 0 %>
      <tr>
        <td colspan="3">No job_titles found.</td>
      </tr>
    <% else %>
      <% @job_titles.each do |job_title| %>
        <tr>
          <td><%= job_title.name %></td>
          <% if manage_job_title(job_title.id) %>
            <td>
              <%= link_to "Edit", edit_job_title_path(job_title), class: "btn btn-default" %>
            </td>
            <td>
                <%= link_to 'Delete', job_title, method: :delete, data: { confirm: 'Are you sure you wish to delete this job title?' }, class: "btn btn-danger"  %>
            </td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/job_titles/new.html.erb
<% provide(:title, "New Job Title") %>
<% provide(:button, "Create") %>
<% provide(:kind, "create") %>
<% provide(:heading, "Job Titles") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/job_titles/update.html.erb
<h1>JobTitle#update</h1>
<p>Find me in app/views/job_title/update.html.erb</p>