config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :employees do
    resources :addresses
  end

  resources :users
  resources :departments,      except: [:show]
  resources :job_titles,       except: [:show]
  resources :job_assignments,  except: [:show]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	before_action :set_employee, except: [:show, :new]

  def index
  end

  def new
    @address = Address.new
    @employee = Employee.find(params[:employee_id])
  end

  def create
    @employee.addresses.create(address_params)

    if @employee.save
      redirect_to employee_addresses_path, notice: "The address has been added!" and return
    end
    flash.now[:danger] = 'Fill out all fields'
    render 'new'
  end

  def edit
    @employee = Employee.find(params[:employee_id])
    @address = @employee.addresses.find(params[:id])
  end

  def update
    @address = @employee.addresses.find(params[:id])
    if @address.update_attributes(address_params)
      redirect_to employee_addresses_path, notice: 'The address has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @address = @employee.addresses.find(params[:id])
    @address.destroy
    redirect_to employee_addresses_path, notice: 'The address has been deleted!' and return
  end

  private
    def set_employee
      @employee = Employee.find(params[:employee_id])
    end

    def address_params
      params.require(:address).permit(:line, :city, :state, :country, :employee_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@employee, @address] do |f| %>

<%= f.label :line, 'Address Line' %>
<%= f.text_field :line, class: 'form-control' %>

<%= f.label :city, 'City' %>
<%= f.text_field :city, class: 'form-control' %>

<%= f.label :state, 'State' %>
<%= f.text_field :state, class: 'form-control' %>

<%= f.label :country, 'Country' %>
<%= f.country_select :country, class: 'form-control' %>

<%= f.submit yield(:button), class: "btn btn-primary" %>
<% end %>

app/views/addresses/create.html.erb
<h1>Address#create</h1>
<p>Find me in app/views/address/create.html.erb</p>

app/views/addresses/destroy.html.erb
<h1>Address#destroy</h1>
<p>Find me in app/views/address/destroy.html.erb</p>

app/views/addresses/edit.html.erb
<% provide(:title, "Edit Address") %>
<% provide(:button, "Update") %>
<% provide(:heading, "Employee Address") %>
<% provide(:kind, "update") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/addresses/index.html.erb
<% provide(:title, "Employee Address") %>
<% provide(:heading, "Employee Address") %>
	<div class="well">
    <%= link_to "New Address", new_employee_address_path, class: "btn btn-primary" %>
  </div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th colspan="10"><%= "#{@employee.first_name} #{@employee.middle_name} #{@employee.last_name}" %></th>
    </tr>
    <tr>
      <th>Address Line</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @employee.addresses.size == 0 %>
      <tr>
        <td colspan="10">No addresses found.</td>
      </tr>
    <% else %>
      <% @employee.addresses.each do |address| %>
        <tr>
          <td><%= address.line %></td>
          <td><%= address.city %></td>
          <td><%= address.state %></td>
          <td><%= address.country %></td>
          <td>
            <%= link_to "Edit", edit_employee_address_path(@employee, address), class: "btn btn-default" %>
          </td>
          <td>
            <%= link_to 'Delete', employee_address_path(@employee, address), method: :delete, data: { confirm: 'Are you sure you wish to delete this address?' }, class: "btn btn-danger"  %></td>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/addresses/new.html.erb
<% provide(:title, "Add Address") %>
<% provide(:kind, "create") %>
<% provide(:button, "Create") %>
<% provide(:heading, "Employee Address") %>
<div class="well">
  <%= render "form" %>
</div>

app/views/addresses/update.html.erb
<h1>Address#update</h1>
<p>Find me in app/views/address/update.html.erb</p>