config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :employees do
    resources :addresses
  end

  resources :users
  resources :departments,      except: [:show]
  resources :job_titles,       except: [:show]
  resources :job_assignments,  except: [:show]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address
  include Mongoid::Document
  field :line, 			type: String
  field :city, 			type: String
  field :state, 		type: String
  field :country, 		type: String

  embedded_in :employee

  validates :line, :city, :state, :country, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department
  include Mongoid::Document
  field :name, type: String

  has_many :employees, autosave: true

  validates :name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }, :uniqueness => true
end

app/models/employee.rb
class Employee
	include Mongoid::Document
	field :first_name, 		type: String
	field :middle_name, 	type: String
	field :last_name, 		type: String
	field :birthday, 		type: Date

	belongs_to :department
	has_many :job_assignment, autosave: true
  	embeds_many :addresses
  	accepts_nested_attributes_for :addresses

	validates :first_name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
	validates :last_name, length: { minimum: 5, :message => "What" }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/models/job_assignment.rb
class JobAssignment
  include Mongoid::Document
  field :start_date, type: Date
  field :end_date, type: Date

  belongs_to :job_title
  belongs_to :employee
end

app/models/job_title.rb
class JobTitle
  include Mongoid::Document
  field :name, type: String

  has_many :job_assignment, autosave: true

  validates :name, length: { minimum: 2, :message => "What" }, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }, :uniqueness => true
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :username, type: String
  field :password_digest, type: String
  field :employee_id, type: BSON::ObjectId
  has_secure_password

  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true
  validates :username, :employee_id, :presence => true, :uniqueness => true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	before_action :set_employee, except: [:show, :new]

  def index
  end

  def new
    @address = Address.new
    @employee = Employee.find(params[:employee_id])
  end

  def create
    @employee.addresses.create(address_params)

    if @employee.save
      redirect_to employee_addresses_path, notice: "The address has been added!" and return
    end
    flash.now[:danger] = 'Fill out all fields'
    render 'new'
  end

  def edit
    @employee = Employee.find(params[:employee_id])
    @address = @employee.addresses.find(params[:id])
  end

  def update
    @address = @employee.addresses.find(params[:id])
    if @address.update_attributes(address_params)
      redirect_to employee_addresses_path, notice: 'The address has been updated!' and return
    end
    render 'edit'
  end

  def destroy
    @address = @employee.addresses.find(params[:id])
    @address.destroy
    redirect_to employee_addresses_path, notice: 'The address has been deleted!' and return
  end

  private
    def set_employee
      @employee = Employee.find(params[:employee_id])
    end

    def address_params
      params.require(:address).permit(:line, :city, :state, :country, :employee_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(:username => params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
    @employee = Employee.find(@user.employee_id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "The user has been created!" and return
    end
    render 'new'
  end

  def edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'The user has been updated!' and return
    end

    render 'edit'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, notice: 'The user has been deleted!' and return
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :employee_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_job_helper.rb
module AssignJobHelper
	def display_name(employee)
		"#{employee.first_name} #{employee.middle_name} #{employee.last_name}"
	end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def manage_employee(employee)
		first = Employee.first
		return !(first.id == employee)
	end
end

app/helpers/job_assignments_helper.rb
module JobAssignmentsHelper
end

app/helpers/job_titles_helper.rb
module JobTitlesHelper
	def manage_job_title(job_title)
		first = JobTitle.first
		return !(first.id == job_title)
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
	def log_in(user)
	  session[:user_id] = user.id
	end

	# Returns the current logged-in user (if any).
	def current_user
		if @current_user.nil? && !session[:user_id].nil?
		  @current_user = User.find(session[:user_id])
		else
		  @current_user
		end
	end

	# Check if user is Admin as Job Title
	def admin?
		admin = JobTitle.first
		job_assign = JobAssignment.find_by(job_title_id: admin.id, employee_id: @current_user.employee_id)
	end

	# Returns true if the user is logged in, false otherwise.
	def logged_in?
	    !current_user.nil?
	end

	# Logs out the current user.
	def log_out
	    session.delete(:user_id)
	    @current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def display_name(employee)
		"#{employee.first_name} #{employee.middle_name} #{employee.last_name}"
	end

	def manage_user(user)
		first = User.first
		return !(first.id == user)
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Ruby on Rails and MongoDB
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
    <nav>
    	<ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Home",   root_path %></li>
        <% if logged_in? %>

          <% if admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Manage <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Employee", employees_path %></li>
                <li><%= link_to "Job Title", job_titles_path %></li>
                <li><%= link_to "Department", departments_path %></li>
                <li><%= link_to "User", users_path %></li>
              </ul>
            </li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Login", login_path %></li>
           
        <% end %>
    	</ul>
    </nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:heading) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container">`
      <%= render 'layouts/header' %>
      <h1><%= yield(:title) %></h1>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>